### ISSUE TITLE
[Notebook Issue] lab06 Task 5

### ISSUE THREAD

**Issue by kpuar** [ccsf-math-108/materials-fa22#11]
The autograder passed this task even though I didn't even attempt a solution.

task_05 passed!

task_05 - 1 message: ✅ It seems like your function print_kth_top_movie_year is working correctly!

**Comment by shawnwiggins** [comment]
Thanks for sharing this issue @kpuar!

- [ ] Update auto-grader test in main notebook.
- [ ] Rebuild student and grader notebooks.
- [ ] Check to see if the issue still exists.
- [ ] Push changes to students' notebooks.
