### ISSUE TITLE
hw 04, Task 9

### ISSUE THREAD

**Issue by kpuar** [ccsf-math-108/materials-fa22#13]
Task 9 instructions are as follows:

"At the moment, the **Job** column of the sf table is not sorted (no particular order). Would the arrays you generated in the **Jobs** column of the previous question be the same if we had sorted alphabetically instead before generating them? Explain your answer. To receive full credit, your answer should reference

how the .group method works
how sorting the **Jobs** column would affect this."

I believe this should read, "how sorting the **Job (no s)** column would affect this". It's referencing the column in the original table, not the one that we just generated as arrays for the preceding task.

**Comment by shawnwiggins** [comment]
Thank you for pointing this out! I updated the main notebook in case this will be used in the future.
