### ISSUE TITLE
[Notebook Issue] Project 1, Task 16, Otter check 3 success description is confusing

### ISSUE THREAD

**Issue by codedmeaning** [ccsf-math-108/materials-fa22#16]
**Issue Description**
Upon passing check number 3, the success description gives the incorrect number for Australians living in extreme poverty. It claims that the number should be 301,415, but Otter is actually checking for 110,773. The success description should reflect the number that Otter is checking for.

**Solution**
In `task_16`, change the value for `success_message` to "✅ The number of people estimated to be living in extreme poverty in Australia should be **110,773**."  See the final line in the code below.
```
         "code": ">>> \n>>> # The number of people estimated to be living in extreme poverty \n>>> # in Australia should be 110,773. That's 22,154,687 * 0.005\n>>> # rounded to the nearest integer.\n>>> float(recent_poverty_total.where('geo', 'aus').column(3).item(0)) == 110773\nTrue",
         "failure_message": "❌ ",
         "hidden": false,
         "locked": false,
         "points": 1,
         "success_message": "✅ The number of people estimated to be living in extreme poverty in Australia should be 301,415."
```

**Comment by codedmeaning** [comment]
Forgot link:
[Line 2319 of ccsf-math-108/materials-fa22/project/project1/student/project1.ipynb](https://github.com/ccsf-math-108/materials-fa22/blob/3b1cb2524b8fa693d26d2e6f383099262cd98c3f/project/project1/student/project1.ipynb?short_path=39dc43e#L2319)

**Comment by shawnwiggins** [comment]
I'm sorry I missed this!

- [ ] Update the success_message and failure_message (was blank) for task_16 - 3 to reference 110,773 instead of 301,415.
- [ ] Rebuild the project
- [ ] Push the changes to the students
